### ISSUE TITLE
'hobo new' using Hobo 2.2.4 fails on bundle install (under Ruby 2.2.2)

### ISSUE THREAD

**Issue by enwood** [Hobo/hobo#174]
Small problem with a missing file when creating a new Hobo 2.2.4 app...
```
~/src % gem install hobo
Fetching: hobo_support-2.2.4.gem (100%)
Successfully installed hobo_support-2.2.4
Fetching: dryml-2.2.4.gem (100%)
Building native extensions.  This could take a while...
Successfully installed dryml-2.2.4
Fetching: hobo_fields-2.2.4.gem (100%)
Successfully installed hobo_fields-2.2.4
Fetching: hobo-2.2.4.gem (100%)
Successfully installed hobo-2.2.4
4 gems installed
~/src % hobo new attr_test2
Hobo Command Line Interface 2.2.4
Generating Rails infrastructure...
  ..
  ..
  ..
     gemfile    responders (~> 2.0)
  
 Hobo Setup Wizard 
  Do you want to start the Setup Wizard now?
(Choose 'n' if you need to manually customize any file before running the Wizard.
You can run it later with `hobo g setup_wizard` from the application root dir.) [y|n] y
    => "y"
         run    bundle install from "."
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Volumes/SSD500/Users/tgriffin/.rbenv/versions/2.2.2/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    Errno::ENOENT: No such file or directory @ rb_file_s_stat - manual/multi_model_forms.markdown
      /Volumes/SSD500/Users/tgriffin/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2716:in `stat'
      /Volumes/SSD500/Users/tgriffin/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2716:in `block in validate_permissions'
      /Volumes/SSD500/Users/tgriffin/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2715:in `each'
```

**Comment by enwood** [comment]
Sorry, looks like a problem on my machine as this is happening with 2.2.3 as well.

**Comment by enwood** [comment]
My problem was I'd built the new Hobo project under a Ruby 2.2.2 environment. This chokes bundle install for Hobo. 

Hobo 2.2.4 works as expected with Ruby 2.1.4.

Tim

**Comment by enwood** [comment]
Maybe I'll leave this open? Tim

**Comment by iox** [comment]
Thanks a lot Tim. Yes, let's leave this open, so we can get Ruby 2.2/2.3 support as soon as possible.
